---

- hosts: opendfuser
  roles:
   -   DS
   - { role: DS,
        DS_USER_instance_name: opendj2,
        DS_USER_PORT_ADMIN: 4445,
        DS_USER_PORT_LDAP: 390,
        DS_USER_PORT_LDAPS: 637,
        DS_USER_PORT_HTTP: 8282,
        DS_USER_PORT_HTTPS: 8446 }
   - { role: Replication,
        Admin_port2_User: 4445,
        DS_PORT_REP2: 8991 }
  vars_files:
   - vars/main.yml