---

- hosts: opendjBackend
  roles:
   - role: DS_Backend
   - role: DS_Backend  
        DS_CONF_instance_name: backend2
        DS_CONF_PORT_ADMIN: 4445
        DS_CONF_PORT_LDAP: 390
        DS_CONF_PORT_LDAPS: 637
        DS_CONF_PORT_JMX: 1690
        DS_CONF_PORT_HTTP: 8282
        DS_CONF_PORT_HTTPS: 8446
   - role: Replication 
     vars:
        Admin_port2_Backend: 4445
        DS_PORT_REP2: 8990
  vars_files:
   - vars/main.yml