---
- hosts: all
  roles:
   - { role: install-base-centos }
  vars_files:
   - vars/main.yml
  
- hosts: AM
  roles:
   - { role: Tomcat }
  vars_files:
   - vars/main.yml
   
- hosts: opendjBackend
  roles:
   - { role: DS_Backend }
  vars_files:
   - vars/main.yml

- hosts: opendfuser
  roles:
   - { role: DS }
  vars_files:
   - vars/main.yml

- hosts: AM
  roles:
   - { role: AM }
  vars_files:
   - vars/main.yml

   