---
# This role installs opendj. It will listen on the default ports (389/636 for ssl)
# Assumes 'java' is installed and on the path
# TODO: Import sample ldif, schema
#
  
- name: create install root
  file: 
    path: {{install_root}} 
    state: directory
 
- name: unpack opendj
  unarchive: 
    copy: no 
    src: "{{ staging_dir }}/{{opendj_zip}}" 
    dest: "{{install_root}}/{{opendj_service_name}}"

- name: copy opendj props file
  template: 
    src: opendj.properties 
    dest: /tmp/opendj.properties 
  
- name: setup opendj
  command: "{{install_root}}/opendj/config {{install_root}}/opendj/setup --cli --propertiesFilePath /tmp/opendj.properties --acceptLicense --generateSelfSignedCertificate --no-prompt "

- name: Create rc script
  command: "{{install_root}}/opendj/bin/create-rc-script -f /etc/init.d/{{opendj_service_name}} -u root"
  
- name: Change the ownership on the files so the fr user can execute ldap commands
  file: 
    path: {{install_root}}/{{opendj_service_name}} 
    state: directory 
    owner: {{fr_user}} 
    recurse: yes

# Ignore errors as the installer may start DJ
- name: Enable opendj - ignore errors as it may already be running
  service: 
    name:{{opendj_service_name}} 
    enabled: yes
  ignore_errors: yes

- name: Copie du fichier ldif
  template: 
    src: admins.ldif
    dest: /tmp/admins.ldif

- name: Création du compte admin openam
  command: "{{install_root}}/opendj/bin/ldapmodify  --port {{opendj_ldap_port}} --bindDN {{opendj_rootUserDN}} --bindPassword {{opendj_password}} --trustAll /tmp/admins.ldif"
  
- name: Modification des aci pour le compte Admin openam
  command: "{{install_root}}/opendj/bin/dsconfig set-access-control-handler-prop --no-prompt --trustAll --add 'global-aci:(target="ldap:///cn=schema")(targetattr="attributeTypes||objectClasses")(version 3.0; acl "Modify schema"; allow (write) userdn="ldap:///uid=openam,ou=admins,{{opendj_basedn}}";)'

- name: Copie du fichier ldif
  template: 
    src: droit_admin.ldif
    dest: /tmp/droit_admin.ldif
 
- name: Création du compte admin openam
  command: "{{install_root}}/opendj/bin/ldapmodify  --port {{opendj_ldap_port}} --bindDN {{opendj_rootUserDN}} --bindPassword {{opendj_password}} --trustAll /tmp/admins.ldif"
