---

- name: Récupération de Tomcat
  get_url: 
    url: http://mirror.ibcp.fr/pub/apache/tomcat/tomcat-9/v9.0.36/bin/apache-tomcat-9.0.36.tar.gz 
    dest: /root/aduneo/apache-tomcat-9.0.36.tar.gz
    mode: 0755
   
#- name: create instance dir and sub dir
#  command: mkdir -p "{{ tomcat_parent }}/{{ tomcat_instance }}/{{item}}"
#  with_items:
#    - conf
#    - webapps
#    - logs
#    - temp
#   - work 

- name: Extraction de Tomcat
  unarchive: 
    src: /root/aduneo/apache-tomcat-9.0.36.tar.gz
    dest: /opt/
    remote_src: yes

- name: Céation d'un lien symbolique vers /opt/tomcat/
  file:
    src: /opt/apache-tomcat-9.0.36/
    dest: /opt/tomcat
    state: link

- name: création de l'utilisateur "{{ tomcat_user }}"
  user:
    name: "{{ tomcat_user }}"
    shell: /bin/false
    home: /opt/tomcat
 

- name: Copie du service Tomcat
  template: 
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service
    mode: 766

- name: Copie du script tomcat.sh permettant de définir le JAVA_HOME
  template: 
    src: tomcat.sh
    dest: /etc/profile.d/
    mode: 755

- name: Change the working directory to somedir/ before executing the command.
  command: "sh /etc/profile.d/tomcat.sh"


#- name: Copy the tomcat defaults to {{tomcat_conf}}
# command: cp "/etc/tomcat/{{item}}" "{{tomcat_conf}}"
#  with_items:
#    - web.xml
#    - context.xml
#    - catalina.policy
#    - catalina.properties

#- name: Configure Tomcat server.xml to set ports, etc.
#  template: 
#    src: server.xml 
#    dest: {{tomcat_conf}}

- name: Configurer un user Tomcat
  template: 
    src: tomcat-users.xml 
    dest: "{{ tomcat_conf }}"
    

- name: Donner à l'utilisateur "{{ tomcat_user }}" les droits sur le dossier "{{ tomcat_parent }}"
  file: 
    path: "{{ tomcat_parent }}" 
    owner: "{{ tomcat_user }}" 
    state: directory 
    recurse: yes

- name: Activer et démarrer le service Tomcat
  service: 
    name: "tomcat.service" 
    state: restarted 
    enabled: yes
