- name: Install tomcat
  yum:
    name: tomcat
    state: latest

- name: create instance dir and sub dir
  command: mkdir -p "{{ tomcat_parent }}/{{ tomcat_instance }}/{{item}}"
  with_items:
    - conf
    - webapps
    - logs
    - temp
    - work

- name: Set JAVA_OPTS in /etc/tomcat/tomcat.conf
  lineinfile: 
    dest: /etc/tomcat/tomcat.conf  
    regexp: '^JAVA_OPTS' 
    line: 'JAVA_OPTS="-Xmx1024m -XX:MaxPermSize=256m"'

- name: Copy the tomcat defaults to {{tomcat_conf}}
  command: cp "/etc/tomcat/{{item}}" "{{tomcat_conf}}"
  with_items:
    - web.xml
    - context.xml
    - catalina.policy
    - catalina.properties

- name: Configure Tomcat server.xml to set ports, etc.
  template: 
    src: server.xml 
    dest: {{tomcat_conf}}

- name: Configure Tomcat users
  template: 
    src: tomcat-users.xml 
    dest: {{tomcat_conf}}

- name: Change ownership of Tomcat installation
  file: 
    path: {{ tomcat_instance_home }} 
    owner: {{ tomcat_user }} 
    state: directory 
    recurse: yes

- name: Enable  and start Tomcat
  service: 
    name: "tomcat@{{ tomcat_instance }}.service" 
    state: restarted 
    enabled: yes
